version: '3.9'
services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: therian
      POSTGRES_PASSWORD: therian
      POSTGRES_DB: therians_app
    ports:
<<<<<<< HEAD
      - "5454:5432"
=======
      - "5432:5432"
>>>>>>> d3f7c4cfbe9221fa4d1a02d569bbafb5abcbc026
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
